### ISSUE TITLE
ES loading speed becomes slow as the number of ROMs increases.

### ISSUE THREAD

**Issue by sana2dang** [OtherCrashOverride/emulationstation-go2#1]
Hello.

ES loading speed becomes slow as the number of ROMs increases.

Can I apply the Loading speed Improvements on the link?

https://github.com/RetroPie/EmulationStation/pull/590/files?file-filters%5B%5D=

https://github.com/fabricecaruso/EmulationStation/commit/f7e49182d8e2396ce8fb81a8c4baf46bc4260ab8

**Comment by f1vefour** [comment]
I don't see a reason you couldn't try.
